Repository nimilaJay/IT3040_ITPM_GRP_83, pull requests merged in 2023-05, with the labels that each got.

#8 Update employee route
  backend/routes/employees.js
Labels: enhancement, good first issue

#15 Update Routes
  backend/routes/Quarter_Performance.js
  backend/routes/private.js
Labels: enhancement, good first issue

#35 update inventoryRepair
  backend/routes/laptopRepair.js
Labels: enhancement, good first issue

#36 Add Frontend common
  frontend/component/common/ProgressBar/progress.js
  frontend/component/common/clock/Clock.js
  frontend/component/common/footer/Footer.css
  frontend/component/common/footer/Footer.js
  frontend/component/common/footer/Footer.test.js
  frontend/component/common/navbar/Navbar.css
  frontend/component/common/navbar/Navbar.jsx
Labels: enhancement

#39 updates salaries routes
  backend/routes/salaries.js
Labels: enhancement

#40 Add frontend cards
  frontend/src/component/TopSpeakerCard/SpeakerCardStyle.css
  frontend/src/component/TopSpeakerCard/TopSpeakerCard.jsx
Labels: good first issue

#44 Add utils
  backend/utils/sendEmail.js
Labels: enhancement, good first issue

#45 Add ErrorResponse util
  backend/utils/errorResponse.js
Labels: enhancement

#46 Add authJS backend
  backend/middleware/auth.js
Labels: enhancement, good first issue

#47 Update middkeware
  backend/middleware/error.js
Labels: enhancement

#67 Admin Executive Update
  frontend/src/modules/AdminModules/CreateExecutive.jsx
Labels: enhancement

#71 calSalary
  frontend/src/modules/AdminModules/CreateMSalary.jsx
Labels: enhancement

#73 Payroll&profile
  frontend/src/modules/AdminModules/CreatePayroll.jsx
  frontend/src/modules/AdminModules/CreateProfile.jsx
Labels: enhancement
